/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Association</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.Association#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.graces.mydsl.myDsl.MyDslPackage#getAssociation()
 * @model
 * @generated
 */
public interface Association extends GenericAssociation
{
  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(AssociationBody)
   * @see org.graces.mydsl.myDsl.MyDslPackage#getAssociation_Body()
   * @model containment="true"
   * @generated
   */
  AssociationBody getBody();

  /**
   * Sets the value of the '{@link org.graces.mydsl.myDsl.Association#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(AssociationBody value);

} // Association
