/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attr Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.AttrBody#getAttrname <em>Attrname</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.AttrBody#getAttrtype <em>Attrtype</em>}</li>
 * </ul>
 *
 * @see org.graces.mydsl.myDsl.MyDslPackage#getAttrBody()
 * @model
 * @generated
 */
public interface AttrBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Attrname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attrname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attrname</em>' attribute.
   * @see #setAttrname(String)
   * @see org.graces.mydsl.myDsl.MyDslPackage#getAttrBody_Attrname()
   * @model
   * @generated
   */
  String getAttrname();

  /**
   * Sets the value of the '{@link org.graces.mydsl.myDsl.AttrBody#getAttrname <em>Attrname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attrname</em>' attribute.
   * @see #getAttrname()
   * @generated
   */
  void setAttrname(String value);

  /**
   * Returns the value of the '<em><b>Attrtype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attrtype</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attrtype</em>' attribute.
   * @see #setAttrtype(String)
   * @see org.graces.mydsl.myDsl.MyDslPackage#getAttrBody_Attrtype()
   * @model
   * @generated
   */
  String getAttrtype();

  /**
   * Sets the value of the '{@link org.graces.mydsl.myDsl.AttrBody#getAttrtype <em>Attrtype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attrtype</em>' attribute.
   * @see #getAttrtype()
   * @generated
   */
  void setAttrtype(String value);

} // AttrBody
