/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.graces.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.graces.org/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.graces.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ModelImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Clazzes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CLAZZES = 1;

  /**
   * The feature id for the '<em><b>Relationships</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__RELATIONSHIPS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 1;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__HEADER = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__BODY = 1;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassHeaderImpl <em>Class Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassHeaderImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassHeader()
   * @generated
   */
  int CLASS_HEADER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_HEADER__NAME = 0;

  /**
   * The number of structural features of the '<em>Class Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_HEADER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassBodyImpl <em>Class Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassBody()
   * @generated
   */
  int CLASS_BODY = 3;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY__ATTRIBUTES = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY__OPERATIONS = 1;

  /**
   * The number of structural features of the '<em>Class Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl <em>Attr Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AttrBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAttrBody()
   * @generated
   */
  int ATTR_BODY = 4;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__TYPE = 2;

  /**
   * The number of structural features of the '<em>Attr Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.OpBodyImpl <em>Op Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.OpBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getOpBody()
   * @generated
   */
  int OP_BODY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__NAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__ARGS = 1;

  /**
   * The feature id for the '<em><b>Return</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__RETURN = 2;

  /**
   * The number of structural features of the '<em>Op Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ReturnBodyImpl <em>Return Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ReturnBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getReturnBody()
   * @generated
   */
  int RETURN_BODY = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_BODY__TYPE = 0;

  /**
   * The number of structural features of the '<em>Return Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_BODY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl <em>Arg Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ArgBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getArgBody()
   * @generated
   */
  int ARG_BODY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Arg Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.GenericAssociationImpl <em>Generic Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.GenericAssociationImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getGenericAssociation()
   * @generated
   */
  int GENERIC_ASSOCIATION = 8;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERIC_ASSOCIATION__HEADER = 0;

  /**
   * The number of structural features of the '<em>Generic Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERIC_ASSOCIATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.RealizationImpl <em>Realization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.RealizationImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getRealization()
   * @generated
   */
  int REALIZATION = 9;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION__HEADER = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION__BODY = 1;

  /**
   * The number of structural features of the '<em>Realization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.RealizationBodyImpl <em>Realization Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.RealizationBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getRealizationBody()
   * @generated
   */
  int REALIZATION_BODY = 10;

  /**
   * The feature id for the '<em><b>Firstend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION_BODY__FIRSTEND = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION_BODY__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Secondend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION_BODY__SECONDEND = 2;

  /**
   * The number of structural features of the '<em>Realization Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REALIZATION_BODY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.CompositionImpl <em>Composition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.CompositionImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getComposition()
   * @generated
   */
  int COMPOSITION = 11;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__HEADER = GENERIC_ASSOCIATION__HEADER;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION__BODY = GENERIC_ASSOCIATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Composition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_FEATURE_COUNT = GENERIC_ASSOCIATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.CompositionBodyImpl <em>Composition Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.CompositionBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getCompositionBody()
   * @generated
   */
  int COMPOSITION_BODY = 12;

  /**
   * The feature id for the '<em><b>Firstendmult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_BODY__FIRSTENDMULT = 0;

  /**
   * The feature id for the '<em><b>Firstend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_BODY__FIRSTEND = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_BODY__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Secondendmult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_BODY__SECONDENDMULT = 3;

  /**
   * The feature id for the '<em><b>Secondend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_BODY__SECONDEND = 4;

  /**
   * The number of structural features of the '<em>Composition Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITION_BODY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AggregationImpl <em>Aggregation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AggregationImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAggregation()
   * @generated
   */
  int AGGREGATION = 13;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__HEADER = GENERIC_ASSOCIATION__HEADER;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION__BODY = GENERIC_ASSOCIATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Aggregation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_FEATURE_COUNT = GENERIC_ASSOCIATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AggregationBodyImpl <em>Aggregation Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AggregationBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAggregationBody()
   * @generated
   */
  int AGGREGATION_BODY = 14;

  /**
   * The feature id for the '<em><b>Firstendmult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_BODY__FIRSTENDMULT = 0;

  /**
   * The feature id for the '<em><b>Firstend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_BODY__FIRSTEND = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_BODY__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Secondendmult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_BODY__SECONDENDMULT = 3;

  /**
   * The feature id for the '<em><b>Secondend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_BODY__SECONDEND = 4;

  /**
   * The number of structural features of the '<em>Aggregation Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATION_BODY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AssociationImpl <em>Association</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AssociationImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAssociation()
   * @generated
   */
  int ASSOCIATION = 15;

  /**
   * The feature id for the '<em><b>Header</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__HEADER = GENERIC_ASSOCIATION__HEADER;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION__BODY = GENERIC_ASSOCIATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Association</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FEATURE_COUNT = GENERIC_ASSOCIATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AssociationBodyImpl <em>Association Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AssociationBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAssociationBody()
   * @generated
   */
  int ASSOCIATION_BODY = 16;

  /**
   * The feature id for the '<em><b>Firstendmult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_BODY__FIRSTENDMULT = 0;

  /**
   * The feature id for the '<em><b>Firstend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_BODY__FIRSTEND = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_BODY__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Secondendmult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_BODY__SECONDENDMULT = 3;

  /**
   * The feature id for the '<em><b>Secondend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_BODY__SECONDEND = 4;

  /**
   * The number of structural features of the '<em>Association Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_BODY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.MultiImpl <em>Multi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.MultiImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getMulti()
   * @generated
   */
  int MULTI = 17;

  /**
   * The feature id for the '<em><b>Multlow</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__MULTLOW = 0;

  /**
   * The feature id for the '<em><b>Multup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__MULTUP = 1;

  /**
   * The feature id for the '<em><b>Multupunbound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__MULTUPUNBOUND = 2;

  /**
   * The feature id for the '<em><b>Multdownunbound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__MULTDOWNUNBOUND = 3;

  /**
   * The number of structural features of the '<em>Multi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.graces.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.Model#getClazzes <em>Clazzes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clazzes</em>'.
   * @see org.graces.mydsl.myDsl.Model#getClazzes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Clazzes();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.Model#getRelationships <em>Relationships</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relationships</em>'.
   * @see org.graces.mydsl.myDsl.Model#getRelationships()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Relationships();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see org.graces.mydsl.myDsl.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Class#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.graces.mydsl.myDsl.Class#getHeader()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Header();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Class#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.Class#getBody()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassHeader <em>Class Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Header</em>'.
   * @see org.graces.mydsl.myDsl.ClassHeader
   * @generated
   */
  EClass getClassHeader();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ClassHeader#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.ClassHeader#getName()
   * @see #getClassHeader()
   * @generated
   */
  EAttribute getClassHeader_Name();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassBody <em>Class Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Body</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody
   * @generated
   */
  EClass getClassBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.ClassBody#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody#getAttributes()
   * @see #getClassBody()
   * @generated
   */
  EReference getClassBody_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.ClassBody#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody#getOperations()
   * @see #getClassBody()
   * @generated
   */
  EReference getClassBody_Operations();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.AttrBody <em>Attr Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Body</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody
   * @generated
   */
  EClass getAttrBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getVisibility()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Visibility();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getName()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Name();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getType()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Type();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.OpBody <em>Op Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Body</em>'.
   * @see org.graces.mydsl.myDsl.OpBody
   * @generated
   */
  EClass getOpBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.OpBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getName()
   * @see #getOpBody()
   * @generated
   */
  EAttribute getOpBody_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.OpBody#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getArgs()
   * @see #getOpBody()
   * @generated
   */
  EReference getOpBody_Args();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.OpBody#getReturn <em>Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getReturn()
   * @see #getOpBody()
   * @generated
   */
  EReference getOpBody_Return();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ReturnBody <em>Return Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Return Body</em>'.
   * @see org.graces.mydsl.myDsl.ReturnBody
   * @generated
   */
  EClass getReturnBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ReturnBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.graces.mydsl.myDsl.ReturnBody#getType()
   * @see #getReturnBody()
   * @generated
   */
  EAttribute getReturnBody_Type();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ArgBody <em>Arg Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arg Body</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody
   * @generated
   */
  EClass getArgBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ArgBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody#getName()
   * @see #getArgBody()
   * @generated
   */
  EAttribute getArgBody_Name();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ArgBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody#getType()
   * @see #getArgBody()
   * @generated
   */
  EAttribute getArgBody_Type();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.GenericAssociation <em>Generic Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Generic Association</em>'.
   * @see org.graces.mydsl.myDsl.GenericAssociation
   * @generated
   */
  EClass getGenericAssociation();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.GenericAssociation#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Header</em>'.
   * @see org.graces.mydsl.myDsl.GenericAssociation#getHeader()
   * @see #getGenericAssociation()
   * @generated
   */
  EAttribute getGenericAssociation_Header();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Realization <em>Realization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Realization</em>'.
   * @see org.graces.mydsl.myDsl.Realization
   * @generated
   */
  EClass getRealization();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Realization#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Header</em>'.
   * @see org.graces.mydsl.myDsl.Realization#getHeader()
   * @see #getRealization()
   * @generated
   */
  EAttribute getRealization_Header();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Realization#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.Realization#getBody()
   * @see #getRealization()
   * @generated
   */
  EReference getRealization_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.RealizationBody <em>Realization Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Realization Body</em>'.
   * @see org.graces.mydsl.myDsl.RealizationBody
   * @generated
   */
  EClass getRealizationBody();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.RealizationBody#getFirstend <em>Firstend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Firstend</em>'.
   * @see org.graces.mydsl.myDsl.RealizationBody#getFirstend()
   * @see #getRealizationBody()
   * @generated
   */
  EReference getRealizationBody_Firstend();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.RealizationBody#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.graces.mydsl.myDsl.RealizationBody#getDescription()
   * @see #getRealizationBody()
   * @generated
   */
  EAttribute getRealizationBody_Description();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.RealizationBody#getSecondend <em>Secondend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Secondend</em>'.
   * @see org.graces.mydsl.myDsl.RealizationBody#getSecondend()
   * @see #getRealizationBody()
   * @generated
   */
  EReference getRealizationBody_Secondend();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Composition <em>Composition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composition</em>'.
   * @see org.graces.mydsl.myDsl.Composition
   * @generated
   */
  EClass getComposition();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Composition#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.Composition#getBody()
   * @see #getComposition()
   * @generated
   */
  EReference getComposition_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.CompositionBody <em>Composition Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composition Body</em>'.
   * @see org.graces.mydsl.myDsl.CompositionBody
   * @generated
   */
  EClass getCompositionBody();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.CompositionBody#getFirstendmult <em>Firstendmult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Firstendmult</em>'.
   * @see org.graces.mydsl.myDsl.CompositionBody#getFirstendmult()
   * @see #getCompositionBody()
   * @generated
   */
  EReference getCompositionBody_Firstendmult();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.CompositionBody#getFirstend <em>Firstend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Firstend</em>'.
   * @see org.graces.mydsl.myDsl.CompositionBody#getFirstend()
   * @see #getCompositionBody()
   * @generated
   */
  EReference getCompositionBody_Firstend();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.CompositionBody#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.graces.mydsl.myDsl.CompositionBody#getDescription()
   * @see #getCompositionBody()
   * @generated
   */
  EAttribute getCompositionBody_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.CompositionBody#getSecondendmult <em>Secondendmult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secondendmult</em>'.
   * @see org.graces.mydsl.myDsl.CompositionBody#getSecondendmult()
   * @see #getCompositionBody()
   * @generated
   */
  EReference getCompositionBody_Secondendmult();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.CompositionBody#getSecondend <em>Secondend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Secondend</em>'.
   * @see org.graces.mydsl.myDsl.CompositionBody#getSecondend()
   * @see #getCompositionBody()
   * @generated
   */
  EReference getCompositionBody_Secondend();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Aggregation <em>Aggregation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aggregation</em>'.
   * @see org.graces.mydsl.myDsl.Aggregation
   * @generated
   */
  EClass getAggregation();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Aggregation#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.Aggregation#getBody()
   * @see #getAggregation()
   * @generated
   */
  EReference getAggregation_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.AggregationBody <em>Aggregation Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aggregation Body</em>'.
   * @see org.graces.mydsl.myDsl.AggregationBody
   * @generated
   */
  EClass getAggregationBody();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.AggregationBody#getFirstendmult <em>Firstendmult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Firstendmult</em>'.
   * @see org.graces.mydsl.myDsl.AggregationBody#getFirstendmult()
   * @see #getAggregationBody()
   * @generated
   */
  EReference getAggregationBody_Firstendmult();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.AggregationBody#getFirstend <em>Firstend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Firstend</em>'.
   * @see org.graces.mydsl.myDsl.AggregationBody#getFirstend()
   * @see #getAggregationBody()
   * @generated
   */
  EReference getAggregationBody_Firstend();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AggregationBody#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.graces.mydsl.myDsl.AggregationBody#getDescription()
   * @see #getAggregationBody()
   * @generated
   */
  EAttribute getAggregationBody_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.AggregationBody#getSecondendmult <em>Secondendmult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secondendmult</em>'.
   * @see org.graces.mydsl.myDsl.AggregationBody#getSecondendmult()
   * @see #getAggregationBody()
   * @generated
   */
  EReference getAggregationBody_Secondendmult();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.AggregationBody#getSecondend <em>Secondend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Secondend</em>'.
   * @see org.graces.mydsl.myDsl.AggregationBody#getSecondend()
   * @see #getAggregationBody()
   * @generated
   */
  EReference getAggregationBody_Secondend();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Association <em>Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association</em>'.
   * @see org.graces.mydsl.myDsl.Association
   * @generated
   */
  EClass getAssociation();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Association#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.Association#getBody()
   * @see #getAssociation()
   * @generated
   */
  EReference getAssociation_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.AssociationBody <em>Association Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Association Body</em>'.
   * @see org.graces.mydsl.myDsl.AssociationBody
   * @generated
   */
  EClass getAssociationBody();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.AssociationBody#getFirstendmult <em>Firstendmult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Firstendmult</em>'.
   * @see org.graces.mydsl.myDsl.AssociationBody#getFirstendmult()
   * @see #getAssociationBody()
   * @generated
   */
  EReference getAssociationBody_Firstendmult();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.AssociationBody#getFirstend <em>Firstend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Firstend</em>'.
   * @see org.graces.mydsl.myDsl.AssociationBody#getFirstend()
   * @see #getAssociationBody()
   * @generated
   */
  EReference getAssociationBody_Firstend();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AssociationBody#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.graces.mydsl.myDsl.AssociationBody#getDescription()
   * @see #getAssociationBody()
   * @generated
   */
  EAttribute getAssociationBody_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.AssociationBody#getSecondendmult <em>Secondendmult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secondendmult</em>'.
   * @see org.graces.mydsl.myDsl.AssociationBody#getSecondendmult()
   * @see #getAssociationBody()
   * @generated
   */
  EReference getAssociationBody_Secondendmult();

  /**
   * Returns the meta object for the reference '{@link org.graces.mydsl.myDsl.AssociationBody#getSecondend <em>Secondend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Secondend</em>'.
   * @see org.graces.mydsl.myDsl.AssociationBody#getSecondend()
   * @see #getAssociationBody()
   * @generated
   */
  EReference getAssociationBody_Secondend();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Multi <em>Multi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multi</em>'.
   * @see org.graces.mydsl.myDsl.Multi
   * @generated
   */
  EClass getMulti();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Multi#getMultlow <em>Multlow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multlow</em>'.
   * @see org.graces.mydsl.myDsl.Multi#getMultlow()
   * @see #getMulti()
   * @generated
   */
  EAttribute getMulti_Multlow();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Multi#getMultup <em>Multup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multup</em>'.
   * @see org.graces.mydsl.myDsl.Multi#getMultup()
   * @see #getMulti()
   * @generated
   */
  EAttribute getMulti_Multup();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Multi#getMultupunbound <em>Multupunbound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multupunbound</em>'.
   * @see org.graces.mydsl.myDsl.Multi#getMultupunbound()
   * @see #getMulti()
   * @generated
   */
  EAttribute getMulti_Multupunbound();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Multi#getMultdownunbound <em>Multdownunbound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multdownunbound</em>'.
   * @see org.graces.mydsl.myDsl.Multi#getMultdownunbound()
   * @see #getMulti()
   * @generated
   */
  EAttribute getMulti_Multdownunbound();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ModelImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Clazzes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CLAZZES = eINSTANCE.getModel_Clazzes();

    /**
     * The meta object literal for the '<em><b>Relationships</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__RELATIONSHIPS = eINSTANCE.getModel_Relationships();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__HEADER = eINSTANCE.getClass_Header();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__BODY = eINSTANCE.getClass_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassHeaderImpl <em>Class Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassHeaderImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassHeader()
     * @generated
     */
    EClass CLASS_HEADER = eINSTANCE.getClassHeader();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_HEADER__NAME = eINSTANCE.getClassHeader_Name();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassBodyImpl <em>Class Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassBody()
     * @generated
     */
    EClass CLASS_BODY = eINSTANCE.getClassBody();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_BODY__ATTRIBUTES = eINSTANCE.getClassBody_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_BODY__OPERATIONS = eINSTANCE.getClassBody_Operations();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl <em>Attr Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AttrBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAttrBody()
     * @generated
     */
    EClass ATTR_BODY = eINSTANCE.getAttrBody();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__VISIBILITY = eINSTANCE.getAttrBody_Visibility();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__NAME = eINSTANCE.getAttrBody_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__TYPE = eINSTANCE.getAttrBody_Type();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.OpBodyImpl <em>Op Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.OpBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getOpBody()
     * @generated
     */
    EClass OP_BODY = eINSTANCE.getOpBody();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_BODY__NAME = eINSTANCE.getOpBody_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BODY__ARGS = eINSTANCE.getOpBody_Args();

    /**
     * The meta object literal for the '<em><b>Return</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BODY__RETURN = eINSTANCE.getOpBody_Return();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ReturnBodyImpl <em>Return Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ReturnBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getReturnBody()
     * @generated
     */
    EClass RETURN_BODY = eINSTANCE.getReturnBody();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RETURN_BODY__TYPE = eINSTANCE.getReturnBody_Type();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl <em>Arg Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ArgBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getArgBody()
     * @generated
     */
    EClass ARG_BODY = eINSTANCE.getArgBody();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_BODY__NAME = eINSTANCE.getArgBody_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_BODY__TYPE = eINSTANCE.getArgBody_Type();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.GenericAssociationImpl <em>Generic Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.GenericAssociationImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getGenericAssociation()
     * @generated
     */
    EClass GENERIC_ASSOCIATION = eINSTANCE.getGenericAssociation();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERIC_ASSOCIATION__HEADER = eINSTANCE.getGenericAssociation_Header();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.RealizationImpl <em>Realization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.RealizationImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getRealization()
     * @generated
     */
    EClass REALIZATION = eINSTANCE.getRealization();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REALIZATION__HEADER = eINSTANCE.getRealization_Header();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REALIZATION__BODY = eINSTANCE.getRealization_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.RealizationBodyImpl <em>Realization Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.RealizationBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getRealizationBody()
     * @generated
     */
    EClass REALIZATION_BODY = eINSTANCE.getRealizationBody();

    /**
     * The meta object literal for the '<em><b>Firstend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REALIZATION_BODY__FIRSTEND = eINSTANCE.getRealizationBody_Firstend();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REALIZATION_BODY__DESCRIPTION = eINSTANCE.getRealizationBody_Description();

    /**
     * The meta object literal for the '<em><b>Secondend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REALIZATION_BODY__SECONDEND = eINSTANCE.getRealizationBody_Secondend();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.CompositionImpl <em>Composition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.CompositionImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getComposition()
     * @generated
     */
    EClass COMPOSITION = eINSTANCE.getComposition();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSITION__BODY = eINSTANCE.getComposition_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.CompositionBodyImpl <em>Composition Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.CompositionBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getCompositionBody()
     * @generated
     */
    EClass COMPOSITION_BODY = eINSTANCE.getCompositionBody();

    /**
     * The meta object literal for the '<em><b>Firstendmult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSITION_BODY__FIRSTENDMULT = eINSTANCE.getCompositionBody_Firstendmult();

    /**
     * The meta object literal for the '<em><b>Firstend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSITION_BODY__FIRSTEND = eINSTANCE.getCompositionBody_Firstend();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSITION_BODY__DESCRIPTION = eINSTANCE.getCompositionBody_Description();

    /**
     * The meta object literal for the '<em><b>Secondendmult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSITION_BODY__SECONDENDMULT = eINSTANCE.getCompositionBody_Secondendmult();

    /**
     * The meta object literal for the '<em><b>Secondend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSITION_BODY__SECONDEND = eINSTANCE.getCompositionBody_Secondend();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AggregationImpl <em>Aggregation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AggregationImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAggregation()
     * @generated
     */
    EClass AGGREGATION = eINSTANCE.getAggregation();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGGREGATION__BODY = eINSTANCE.getAggregation_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AggregationBodyImpl <em>Aggregation Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AggregationBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAggregationBody()
     * @generated
     */
    EClass AGGREGATION_BODY = eINSTANCE.getAggregationBody();

    /**
     * The meta object literal for the '<em><b>Firstendmult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGGREGATION_BODY__FIRSTENDMULT = eINSTANCE.getAggregationBody_Firstendmult();

    /**
     * The meta object literal for the '<em><b>Firstend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGGREGATION_BODY__FIRSTEND = eINSTANCE.getAggregationBody_Firstend();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGGREGATION_BODY__DESCRIPTION = eINSTANCE.getAggregationBody_Description();

    /**
     * The meta object literal for the '<em><b>Secondendmult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGGREGATION_BODY__SECONDENDMULT = eINSTANCE.getAggregationBody_Secondendmult();

    /**
     * The meta object literal for the '<em><b>Secondend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGGREGATION_BODY__SECONDEND = eINSTANCE.getAggregationBody_Secondend();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AssociationImpl <em>Association</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AssociationImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAssociation()
     * @generated
     */
    EClass ASSOCIATION = eINSTANCE.getAssociation();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION__BODY = eINSTANCE.getAssociation_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AssociationBodyImpl <em>Association Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AssociationBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAssociationBody()
     * @generated
     */
    EClass ASSOCIATION_BODY = eINSTANCE.getAssociationBody();

    /**
     * The meta object literal for the '<em><b>Firstendmult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_BODY__FIRSTENDMULT = eINSTANCE.getAssociationBody_Firstendmult();

    /**
     * The meta object literal for the '<em><b>Firstend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_BODY__FIRSTEND = eINSTANCE.getAssociationBody_Firstend();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION_BODY__DESCRIPTION = eINSTANCE.getAssociationBody_Description();

    /**
     * The meta object literal for the '<em><b>Secondendmult</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_BODY__SECONDENDMULT = eINSTANCE.getAssociationBody_Secondendmult();

    /**
     * The meta object literal for the '<em><b>Secondend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_BODY__SECONDEND = eINSTANCE.getAssociationBody_Secondend();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.MultiImpl <em>Multi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.MultiImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getMulti()
     * @generated
     */
    EClass MULTI = eINSTANCE.getMulti();

    /**
     * The meta object literal for the '<em><b>Multlow</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTI__MULTLOW = eINSTANCE.getMulti_Multlow();

    /**
     * The meta object literal for the '<em><b>Multup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTI__MULTUP = eINSTANCE.getMulti_Multup();

    /**
     * The meta object literal for the '<em><b>Multupunbound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTI__MULTUPUNBOUND = eINSTANCE.getMulti_Multupunbound();

    /**
     * The meta object literal for the '<em><b>Multdownunbound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTI__MULTDOWNUNBOUND = eINSTANCE.getMulti_Multdownunbound();

  }

} //MyDslPackage
