/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.graces.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.graces.org/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.graces.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ModelDefinitionImpl <em>Model Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ModelDefinitionImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getModelDefinition()
   * @generated
   */
  int MODEL_DEFINITION = 0;

  /**
   * The feature id for the '<em><b>Modelname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_DEFINITION__MODELNAME = 0;

  /**
   * The number of structural features of the '<em>Model Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassDeclImpl <em>Class Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassDeclImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassDecl()
   * @generated
   */
  int CLASS_DECL = 1;

  /**
   * The feature id for the '<em><b>Modelname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__MODELNAME = MODEL_DEFINITION__MODELNAME;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__HEADER = MODEL_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL__BODY = MODEL_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Class Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_DECL_FEATURE_COUNT = MODEL_DEFINITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassHeaderImpl <em>Class Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassHeaderImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassHeader()
   * @generated
   */
  int CLASS_HEADER = 2;

  /**
   * The feature id for the '<em><b>Classname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_HEADER__CLASSNAME = 0;

  /**
   * The number of structural features of the '<em>Class Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_HEADER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassBodyImpl <em>Class Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassBody()
   * @generated
   */
  int CLASS_BODY = 3;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY__ATTRIBUTES = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY__OPERATIONS = 1;

  /**
   * The number of structural features of the '<em>Class Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl <em>Attr Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AttrBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAttrBody()
   * @generated
   */
  int ATTR_BODY = 4;

  /**
   * The feature id for the '<em><b>Attrname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__ATTRNAME = 0;

  /**
   * The feature id for the '<em><b>Attrtype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__ATTRTYPE = 1;

  /**
   * The number of structural features of the '<em>Attr Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.OpBodyImpl <em>Op Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.OpBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getOpBody()
   * @generated
   */
  int OP_BODY = 5;

  /**
   * The feature id for the '<em><b>Opname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__OPNAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__ARGS = 1;

  /**
   * The feature id for the '<em><b>Returntype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__RETURNTYPE = 2;

  /**
   * The number of structural features of the '<em>Op Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl <em>Arg Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ArgBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getArgBody()
   * @generated
   */
  int ARG_BODY = 6;

  /**
   * The feature id for the '<em><b>Argname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY__ARGNAME = 0;

  /**
   * The feature id for the '<em><b>Argtype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY__ARGTYPE = 1;

  /**
   * The number of structural features of the '<em>Arg Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ModelDefinition <em>Model Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Definition</em>'.
   * @see org.graces.mydsl.myDsl.ModelDefinition
   * @generated
   */
  EClass getModelDefinition();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ModelDefinition#getModelname <em>Modelname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Modelname</em>'.
   * @see org.graces.mydsl.myDsl.ModelDefinition#getModelname()
   * @see #getModelDefinition()
   * @generated
   */
  EAttribute getModelDefinition_Modelname();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassDecl <em>Class Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Decl</em>'.
   * @see org.graces.mydsl.myDsl.ClassDecl
   * @generated
   */
  EClass getClassDecl();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.ClassDecl#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.graces.mydsl.myDsl.ClassDecl#getHeader()
   * @see #getClassDecl()
   * @generated
   */
  EReference getClassDecl_Header();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.ClassDecl#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.ClassDecl#getBody()
   * @see #getClassDecl()
   * @generated
   */
  EReference getClassDecl_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassHeader <em>Class Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Header</em>'.
   * @see org.graces.mydsl.myDsl.ClassHeader
   * @generated
   */
  EClass getClassHeader();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ClassHeader#getClassname <em>Classname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Classname</em>'.
   * @see org.graces.mydsl.myDsl.ClassHeader#getClassname()
   * @see #getClassHeader()
   * @generated
   */
  EAttribute getClassHeader_Classname();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassBody <em>Class Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Body</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody
   * @generated
   */
  EClass getClassBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.ClassBody#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody#getAttributes()
   * @see #getClassBody()
   * @generated
   */
  EReference getClassBody_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.ClassBody#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody#getOperations()
   * @see #getClassBody()
   * @generated
   */
  EReference getClassBody_Operations();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.AttrBody <em>Attr Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Body</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody
   * @generated
   */
  EClass getAttrBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getAttrname <em>Attrname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attrname</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getAttrname()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Attrname();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getAttrtype <em>Attrtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attrtype</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getAttrtype()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Attrtype();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.OpBody <em>Op Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Body</em>'.
   * @see org.graces.mydsl.myDsl.OpBody
   * @generated
   */
  EClass getOpBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.OpBody#getOpname <em>Opname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Opname</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getOpname()
   * @see #getOpBody()
   * @generated
   */
  EAttribute getOpBody_Opname();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.OpBody#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getArgs()
   * @see #getOpBody()
   * @generated
   */
  EReference getOpBody_Args();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.OpBody#getReturntype <em>Returntype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Returntype</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getReturntype()
   * @see #getOpBody()
   * @generated
   */
  EAttribute getOpBody_Returntype();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ArgBody <em>Arg Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arg Body</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody
   * @generated
   */
  EClass getArgBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ArgBody#getArgname <em>Argname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Argname</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody#getArgname()
   * @see #getArgBody()
   * @generated
   */
  EAttribute getArgBody_Argname();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ArgBody#getArgtype <em>Argtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Argtype</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody#getArgtype()
   * @see #getArgBody()
   * @generated
   */
  EAttribute getArgBody_Argtype();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ModelDefinitionImpl <em>Model Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ModelDefinitionImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getModelDefinition()
     * @generated
     */
    EClass MODEL_DEFINITION = eINSTANCE.getModelDefinition();

    /**
     * The meta object literal for the '<em><b>Modelname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_DEFINITION__MODELNAME = eINSTANCE.getModelDefinition_Modelname();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassDeclImpl <em>Class Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassDeclImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassDecl()
     * @generated
     */
    EClass CLASS_DECL = eINSTANCE.getClassDecl();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECL__HEADER = eINSTANCE.getClassDecl_Header();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_DECL__BODY = eINSTANCE.getClassDecl_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassHeaderImpl <em>Class Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassHeaderImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassHeader()
     * @generated
     */
    EClass CLASS_HEADER = eINSTANCE.getClassHeader();

    /**
     * The meta object literal for the '<em><b>Classname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_HEADER__CLASSNAME = eINSTANCE.getClassHeader_Classname();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassBodyImpl <em>Class Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassBody()
     * @generated
     */
    EClass CLASS_BODY = eINSTANCE.getClassBody();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_BODY__ATTRIBUTES = eINSTANCE.getClassBody_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_BODY__OPERATIONS = eINSTANCE.getClassBody_Operations();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl <em>Attr Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AttrBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAttrBody()
     * @generated
     */
    EClass ATTR_BODY = eINSTANCE.getAttrBody();

    /**
     * The meta object literal for the '<em><b>Attrname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__ATTRNAME = eINSTANCE.getAttrBody_Attrname();

    /**
     * The meta object literal for the '<em><b>Attrtype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__ATTRTYPE = eINSTANCE.getAttrBody_Attrtype();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.OpBodyImpl <em>Op Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.OpBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getOpBody()
     * @generated
     */
    EClass OP_BODY = eINSTANCE.getOpBody();

    /**
     * The meta object literal for the '<em><b>Opname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_BODY__OPNAME = eINSTANCE.getOpBody_Opname();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BODY__ARGS = eINSTANCE.getOpBody_Args();

    /**
     * The meta object literal for the '<em><b>Returntype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_BODY__RETURNTYPE = eINSTANCE.getOpBody_Returntype();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl <em>Arg Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ArgBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getArgBody()
     * @generated
     */
    EClass ARG_BODY = eINSTANCE.getArgBody();

    /**
     * The meta object literal for the '<em><b>Argname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_BODY__ARGNAME = eINSTANCE.getArgBody_Argname();

    /**
     * The meta object literal for the '<em><b>Argtype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_BODY__ARGTYPE = eINSTANCE.getArgBody_Argtype();

  }

} //MyDslPackage
