/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.graces.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.graces.org/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.graces.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ModelImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Clazzes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CLAZZES = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 1;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__HEADER = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__BODY = 1;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassHeaderImpl <em>Class Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassHeaderImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassHeader()
   * @generated
   */
  int CLASS_HEADER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_HEADER__NAME = 0;

  /**
   * The number of structural features of the '<em>Class Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_HEADER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ClassBodyImpl <em>Class Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ClassBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassBody()
   * @generated
   */
  int CLASS_BODY = 3;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY__ATTRIBUTES = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY__OPERATIONS = 1;

  /**
   * The number of structural features of the '<em>Class Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl <em>Attr Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.AttrBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAttrBody()
   * @generated
   */
  int ATTR_BODY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Attr Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTR_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.OpBodyImpl <em>Op Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.OpBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getOpBody()
   * @generated
   */
  int OP_BODY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__NAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__ARGS = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY__TYPE = 2;

  /**
   * The number of structural features of the '<em>Op Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_BODY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl <em>Arg Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.graces.mydsl.myDsl.impl.ArgBodyImpl
   * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getArgBody()
   * @generated
   */
  int ARG_BODY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Arg Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARG_BODY_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.graces.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.Model#getClazzes <em>Clazzes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clazzes</em>'.
   * @see org.graces.mydsl.myDsl.Model#getClazzes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Clazzes();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see org.graces.mydsl.myDsl.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Class#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see org.graces.mydsl.myDsl.Class#getHeader()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Header();

  /**
   * Returns the meta object for the containment reference '{@link org.graces.mydsl.myDsl.Class#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.graces.mydsl.myDsl.Class#getBody()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_Body();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassHeader <em>Class Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Header</em>'.
   * @see org.graces.mydsl.myDsl.ClassHeader
   * @generated
   */
  EClass getClassHeader();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ClassHeader#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.ClassHeader#getName()
   * @see #getClassHeader()
   * @generated
   */
  EAttribute getClassHeader_Name();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ClassBody <em>Class Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Body</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody
   * @generated
   */
  EClass getClassBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.ClassBody#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody#getAttributes()
   * @see #getClassBody()
   * @generated
   */
  EReference getClassBody_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.ClassBody#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.graces.mydsl.myDsl.ClassBody#getOperations()
   * @see #getClassBody()
   * @generated
   */
  EReference getClassBody_Operations();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.AttrBody <em>Attr Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attr Body</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody
   * @generated
   */
  EClass getAttrBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getName()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Name();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.AttrBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.graces.mydsl.myDsl.AttrBody#getType()
   * @see #getAttrBody()
   * @generated
   */
  EAttribute getAttrBody_Type();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.OpBody <em>Op Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Body</em>'.
   * @see org.graces.mydsl.myDsl.OpBody
   * @generated
   */
  EClass getOpBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.OpBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getName()
   * @see #getOpBody()
   * @generated
   */
  EAttribute getOpBody_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.graces.mydsl.myDsl.OpBody#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getArgs()
   * @see #getOpBody()
   * @generated
   */
  EReference getOpBody_Args();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.OpBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.graces.mydsl.myDsl.OpBody#getType()
   * @see #getOpBody()
   * @generated
   */
  EAttribute getOpBody_Type();

  /**
   * Returns the meta object for class '{@link org.graces.mydsl.myDsl.ArgBody <em>Arg Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arg Body</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody
   * @generated
   */
  EClass getArgBody();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ArgBody#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody#getName()
   * @see #getArgBody()
   * @generated
   */
  EAttribute getArgBody_Name();

  /**
   * Returns the meta object for the attribute '{@link org.graces.mydsl.myDsl.ArgBody#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.graces.mydsl.myDsl.ArgBody#getType()
   * @see #getArgBody()
   * @generated
   */
  EAttribute getArgBody_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ModelImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Clazzes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CLAZZES = eINSTANCE.getModel_Clazzes();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__HEADER = eINSTANCE.getClass_Header();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__BODY = eINSTANCE.getClass_Body();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassHeaderImpl <em>Class Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassHeaderImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassHeader()
     * @generated
     */
    EClass CLASS_HEADER = eINSTANCE.getClassHeader();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_HEADER__NAME = eINSTANCE.getClassHeader_Name();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ClassBodyImpl <em>Class Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ClassBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getClassBody()
     * @generated
     */
    EClass CLASS_BODY = eINSTANCE.getClassBody();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_BODY__ATTRIBUTES = eINSTANCE.getClassBody_Attributes();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_BODY__OPERATIONS = eINSTANCE.getClassBody_Operations();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl <em>Attr Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.AttrBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getAttrBody()
     * @generated
     */
    EClass ATTR_BODY = eINSTANCE.getAttrBody();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__NAME = eINSTANCE.getAttrBody_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTR_BODY__TYPE = eINSTANCE.getAttrBody_Type();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.OpBodyImpl <em>Op Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.OpBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getOpBody()
     * @generated
     */
    EClass OP_BODY = eINSTANCE.getOpBody();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_BODY__NAME = eINSTANCE.getOpBody_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OP_BODY__ARGS = eINSTANCE.getOpBody_Args();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_BODY__TYPE = eINSTANCE.getOpBody_Type();

    /**
     * The meta object literal for the '{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl <em>Arg Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.graces.mydsl.myDsl.impl.ArgBodyImpl
     * @see org.graces.mydsl.myDsl.impl.MyDslPackageImpl#getArgBody()
     * @generated
     */
    EClass ARG_BODY = eINSTANCE.getArgBody();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_BODY__NAME = eINSTANCE.getArgBody_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARG_BODY__TYPE = eINSTANCE.getArgBody_Type();

  }

} //MyDslPackage
