/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Realization Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.RealizationBody#getFirstend <em>Firstend</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.RealizationBody#getDescription <em>Description</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.RealizationBody#getSecondend <em>Secondend</em>}</li>
 * </ul>
 *
 * @see org.graces.mydsl.myDsl.MyDslPackage#getRealizationBody()
 * @model
 * @generated
 */
public interface RealizationBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Firstend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Firstend</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Firstend</em>' reference.
   * @see #setFirstend(ClassHeader)
   * @see org.graces.mydsl.myDsl.MyDslPackage#getRealizationBody_Firstend()
   * @model
   * @generated
   */
  ClassHeader getFirstend();

  /**
   * Sets the value of the '{@link org.graces.mydsl.myDsl.RealizationBody#getFirstend <em>Firstend</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Firstend</em>' reference.
   * @see #getFirstend()
   * @generated
   */
  void setFirstend(ClassHeader value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.graces.mydsl.myDsl.MyDslPackage#getRealizationBody_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.graces.mydsl.myDsl.RealizationBody#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Secondend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Secondend</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secondend</em>' reference.
   * @see #setSecondend(ClassHeader)
   * @see org.graces.mydsl.myDsl.MyDslPackage#getRealizationBody_Secondend()
   * @model
   * @generated
   */
  ClassHeader getSecondend();

  /**
   * Sets the value of the '{@link org.graces.mydsl.myDsl.RealizationBody#getSecondend <em>Secondend</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secondend</em>' reference.
   * @see #getSecondend()
   * @generated
   */
  void setSecondend(ClassHeader value);

} // RealizationBody
