/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.graces.mydsl.myDsl.ArgBody;
import org.graces.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Arg Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl#getArgname <em>Argname</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.impl.ArgBodyImpl#getArgtype <em>Argtype</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ArgBodyImpl extends MinimalEObjectImpl.Container implements ArgBody
{
  /**
   * The default value of the '{@link #getArgname() <em>Argname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgname()
   * @generated
   * @ordered
   */
  protected static final String ARGNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArgname() <em>Argname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgname()
   * @generated
   * @ordered
   */
  protected String argname = ARGNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getArgtype() <em>Argtype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgtype()
   * @generated
   * @ordered
   */
  protected static final String ARGTYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArgtype() <em>Argtype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgtype()
   * @generated
   * @ordered
   */
  protected String argtype = ARGTYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArgBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ARG_BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getArgname()
  {
    return argname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setArgname(String newArgname)
  {
    String oldArgname = argname;
    argname = newArgname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARG_BODY__ARGNAME, oldArgname, argname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getArgtype()
  {
    return argtype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setArgtype(String newArgtype)
  {
    String oldArgtype = argtype;
    argtype = newArgtype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ARG_BODY__ARGTYPE, oldArgtype, argtype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ARG_BODY__ARGNAME:
        return getArgname();
      case MyDslPackage.ARG_BODY__ARGTYPE:
        return getArgtype();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ARG_BODY__ARGNAME:
        setArgname((String)newValue);
        return;
      case MyDslPackage.ARG_BODY__ARGTYPE:
        setArgtype((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ARG_BODY__ARGNAME:
        setArgname(ARGNAME_EDEFAULT);
        return;
      case MyDslPackage.ARG_BODY__ARGTYPE:
        setArgtype(ARGTYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ARG_BODY__ARGNAME:
        return ARGNAME_EDEFAULT == null ? argname != null : !ARGNAME_EDEFAULT.equals(argname);
      case MyDslPackage.ARG_BODY__ARGTYPE:
        return ARGTYPE_EDEFAULT == null ? argtype != null : !ARGTYPE_EDEFAULT.equals(argtype);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (argname: ");
    result.append(argname);
    result.append(", argtype: ");
    result.append(argtype);
    result.append(')');
    return result.toString();
  }

} //ArgBodyImpl
