/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.graces.mydsl.myDsl.AttrBody;
import org.graces.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attr Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl#getAttrname <em>Attrname</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.impl.AttrBodyImpl#getAttrtype <em>Attrtype</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttrBodyImpl extends MinimalEObjectImpl.Container implements AttrBody
{
  /**
   * The default value of the '{@link #getAttrname() <em>Attrname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrname()
   * @generated
   * @ordered
   */
  protected static final String ATTRNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAttrname() <em>Attrname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrname()
   * @generated
   * @ordered
   */
  protected String attrname = ATTRNAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAttrtype() <em>Attrtype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrtype()
   * @generated
   * @ordered
   */
  protected static final String ATTRTYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAttrtype() <em>Attrtype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrtype()
   * @generated
   * @ordered
   */
  protected String attrtype = ATTRTYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttrBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ATTR_BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAttrname()
  {
    return attrname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttrname(String newAttrname)
  {
    String oldAttrname = attrname;
    attrname = newAttrname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTR_BODY__ATTRNAME, oldAttrname, attrname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAttrtype()
  {
    return attrtype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttrtype(String newAttrtype)
  {
    String oldAttrtype = attrtype;
    attrtype = newAttrtype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ATTR_BODY__ATTRTYPE, oldAttrtype, attrtype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTR_BODY__ATTRNAME:
        return getAttrname();
      case MyDslPackage.ATTR_BODY__ATTRTYPE:
        return getAttrtype();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTR_BODY__ATTRNAME:
        setAttrname((String)newValue);
        return;
      case MyDslPackage.ATTR_BODY__ATTRTYPE:
        setAttrtype((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTR_BODY__ATTRNAME:
        setAttrname(ATTRNAME_EDEFAULT);
        return;
      case MyDslPackage.ATTR_BODY__ATTRTYPE:
        setAttrtype(ATTRTYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ATTR_BODY__ATTRNAME:
        return ATTRNAME_EDEFAULT == null ? attrname != null : !ATTRNAME_EDEFAULT.equals(attrname);
      case MyDslPackage.ATTR_BODY__ATTRTYPE:
        return ATTRTYPE_EDEFAULT == null ? attrtype != null : !ATTRTYPE_EDEFAULT.equals(attrtype);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (attrname: ");
    result.append(attrname);
    result.append(", attrtype: ");
    result.append(attrtype);
    result.append(')');
    return result.toString();
  }

} //AttrBodyImpl
