/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.graces.mydsl.myDsl.ArgBody;
import org.graces.mydsl.myDsl.MyDslPackage;
import org.graces.mydsl.myDsl.OpBody;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Op Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.impl.OpBodyImpl#getOpname <em>Opname</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.impl.OpBodyImpl#getArgs <em>Args</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.impl.OpBodyImpl#getReturntype <em>Returntype</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OpBodyImpl extends MinimalEObjectImpl.Container implements OpBody
{
  /**
   * The default value of the '{@link #getOpname() <em>Opname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpname()
   * @generated
   * @ordered
   */
  protected static final String OPNAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOpname() <em>Opname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpname()
   * @generated
   * @ordered
   */
  protected String opname = OPNAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getArgs() <em>Args</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgs()
   * @generated
   * @ordered
   */
  protected EList<ArgBody> args;

  /**
   * The default value of the '{@link #getReturntype() <em>Returntype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturntype()
   * @generated
   * @ordered
   */
  protected static final String RETURNTYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReturntype() <em>Returntype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturntype()
   * @generated
   * @ordered
   */
  protected String returntype = RETURNTYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OpBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OP_BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOpname()
  {
    return opname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOpname(String newOpname)
  {
    String oldOpname = opname;
    opname = newOpname;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OP_BODY__OPNAME, oldOpname, opname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ArgBody> getArgs()
  {
    if (args == null)
    {
      args = new EObjectContainmentEList<ArgBody>(ArgBody.class, this, MyDslPackage.OP_BODY__ARGS);
    }
    return args;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getReturntype()
  {
    return returntype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReturntype(String newReturntype)
  {
    String oldReturntype = returntype;
    returntype = newReturntype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OP_BODY__RETURNTYPE, oldReturntype, returntype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.OP_BODY__ARGS:
        return ((InternalEList<?>)getArgs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.OP_BODY__OPNAME:
        return getOpname();
      case MyDslPackage.OP_BODY__ARGS:
        return getArgs();
      case MyDslPackage.OP_BODY__RETURNTYPE:
        return getReturntype();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.OP_BODY__OPNAME:
        setOpname((String)newValue);
        return;
      case MyDslPackage.OP_BODY__ARGS:
        getArgs().clear();
        getArgs().addAll((Collection<? extends ArgBody>)newValue);
        return;
      case MyDslPackage.OP_BODY__RETURNTYPE:
        setReturntype((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OP_BODY__OPNAME:
        setOpname(OPNAME_EDEFAULT);
        return;
      case MyDslPackage.OP_BODY__ARGS:
        getArgs().clear();
        return;
      case MyDslPackage.OP_BODY__RETURNTYPE:
        setReturntype(RETURNTYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OP_BODY__OPNAME:
        return OPNAME_EDEFAULT == null ? opname != null : !OPNAME_EDEFAULT.equals(opname);
      case MyDslPackage.OP_BODY__ARGS:
        return args != null && !args.isEmpty();
      case MyDslPackage.OP_BODY__RETURNTYPE:
        return RETURNTYPE_EDEFAULT == null ? returntype != null : !RETURNTYPE_EDEFAULT.equals(returntype);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (opname: ");
    result.append(opname);
    result.append(", returntype: ");
    result.append(returntype);
    result.append(')');
    return result.toString();
  }

} //OpBodyImpl
