/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.graces.mydsl.myDsl.ClassHeader;
import org.graces.mydsl.myDsl.MyDslPackage;
import org.graces.mydsl.myDsl.RealizationBody;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Realization Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.graces.mydsl.myDsl.impl.RealizationBodyImpl#getFirstend <em>Firstend</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.impl.RealizationBodyImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.graces.mydsl.myDsl.impl.RealizationBodyImpl#getSecondend <em>Secondend</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RealizationBodyImpl extends MinimalEObjectImpl.Container implements RealizationBody
{
  /**
   * The cached value of the '{@link #getFirstend() <em>Firstend</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstend()
   * @generated
   * @ordered
   */
  protected ClassHeader firstend;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getSecondend() <em>Secondend</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecondend()
   * @generated
   * @ordered
   */
  protected ClassHeader secondend;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RealizationBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.REALIZATION_BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassHeader getFirstend()
  {
    if (firstend != null && firstend.eIsProxy())
    {
      InternalEObject oldFirstend = (InternalEObject)firstend;
      firstend = (ClassHeader)eResolveProxy(oldFirstend);
      if (firstend != oldFirstend)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.REALIZATION_BODY__FIRSTEND, oldFirstend, firstend));
      }
    }
    return firstend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassHeader basicGetFirstend()
  {
    return firstend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFirstend(ClassHeader newFirstend)
  {
    ClassHeader oldFirstend = firstend;
    firstend = newFirstend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REALIZATION_BODY__FIRSTEND, oldFirstend, firstend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REALIZATION_BODY__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassHeader getSecondend()
  {
    if (secondend != null && secondend.eIsProxy())
    {
      InternalEObject oldSecondend = (InternalEObject)secondend;
      secondend = (ClassHeader)eResolveProxy(oldSecondend);
      if (secondend != oldSecondend)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.REALIZATION_BODY__SECONDEND, oldSecondend, secondend));
      }
    }
    return secondend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ClassHeader basicGetSecondend()
  {
    return secondend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecondend(ClassHeader newSecondend)
  {
    ClassHeader oldSecondend = secondend;
    secondend = newSecondend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.REALIZATION_BODY__SECONDEND, oldSecondend, secondend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.REALIZATION_BODY__FIRSTEND:
        if (resolve) return getFirstend();
        return basicGetFirstend();
      case MyDslPackage.REALIZATION_BODY__DESCRIPTION:
        return getDescription();
      case MyDslPackage.REALIZATION_BODY__SECONDEND:
        if (resolve) return getSecondend();
        return basicGetSecondend();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.REALIZATION_BODY__FIRSTEND:
        setFirstend((ClassHeader)newValue);
        return;
      case MyDslPackage.REALIZATION_BODY__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MyDslPackage.REALIZATION_BODY__SECONDEND:
        setSecondend((ClassHeader)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.REALIZATION_BODY__FIRSTEND:
        setFirstend((ClassHeader)null);
        return;
      case MyDslPackage.REALIZATION_BODY__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MyDslPackage.REALIZATION_BODY__SECONDEND:
        setSecondend((ClassHeader)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.REALIZATION_BODY__FIRSTEND:
        return firstend != null;
      case MyDslPackage.REALIZATION_BODY__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MyDslPackage.REALIZATION_BODY__SECONDEND:
        return secondend != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //RealizationBodyImpl
