/**
 * generated by Xtext 2.13.0
 */
package org.graces.mydsl;

import org.graces.mydsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
